# Generated by Django 3.1.5 on 2022-09-29 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collect', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('excluded', models.BooleanField(db_index=True, default=False)),
                ('excluded_at', models.DateTimeField(blank=True, null=True)),
                ('total_price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=10)),
                ('address_demand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collect.addressdemand')),
                ('excluded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_excluded_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
