# Generated by Django 4.0 on 2022-10-19 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_collector_excluded_by_and_more'),
        ('discard', '0002_order_status_alter_order_excluded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discarder',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.discarder'),
            preserve_default=False,
        ),
    ]
