# Generated by Django 3.1.5 on 2022-09-29 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('excluded', models.BooleanField(db_index=True, default=False)),
                ('excluded_at', models.DateTimeField(blank=True, null=True)),
                ('street', models.CharField(default='', max_length=255)),
                ('district', models.CharField(default='', max_length=255)),
                ('number', models.CharField(default='', max_length=8)),
                ('complement', models.CharField(default='', max_length=25)),
                ('zip_code', models.CharField(default='', max_length=20)),
                ('city', models.CharField(default='', max_length=100)),
                ('state', models.CharField(default='', max_length=50)),
                ('country', models.CharField(default='', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AddressDemand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('excluded', models.BooleanField(db_index=True, default=False)),
                ('excluded_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('excluded', models.BooleanField(db_index=True, default=False)),
                ('excluded_at', models.DateTimeField(blank=True, null=True)),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('max_quantity', models.DecimalField(decimal_places=4, max_digits=10)),
                ('min_quantity', models.DecimalField(decimal_places=4, max_digits=10)),
                ('measure', models.CharField(max_length=25)),
                ('item', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
