# Generated by Django 3.1.5 on 2022-09-29 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('collect', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='demand',
            name='collector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.collector'),
        ),
        migrations.AddField(
            model_name='demand',
            name='excluded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demand_excluded_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='addressdemand',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collect.address'),
        ),
        migrations.AddField(
            model_name='addressdemand',
            name='demand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collect.demand'),
        ),
        migrations.AddField(
            model_name='addressdemand',
            name='excluded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addressdemand_excluded_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='address',
            name='collector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.collector'),
        ),
        migrations.AddField(
            model_name='address',
            name='excluded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='address_excluded_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
