# Generated by Django 4.0 on 2022-10-22 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0003_demand_status_alter_address_excluded_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand',
            name='status',
            field=models.CharField(choices=[('o', 'Open'), ('c', 'Closed')], default='o', max_length=1),
        ),
        migrations.AlterUniqueTogether(
            name='addressdemand',
            unique_together={('address', 'demand')},
        ),
    ]
